{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vesta.fullname" . }}
  labels:
    {{- include "vesta.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.secret.data }}
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
  {{- else }} {}
  {{- end }}
{{- end }}
